<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit)
?>

<ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
    <?= /* @noEscape */
    $_menuHtml ?>
    <?= $block->getChildHtml() ?>
</ul>

<script>
    const topCatagories = document.querySelectorAll('.level0.category-item > a.level-top');

    for (let item of topCatagories) {
        let icon = document.createElement('div');
        icon.classList.add('category-icon');
        icon.innerHTML = '<img src="/static/frontend/Kosher/default/en_US/images/categories/groceries.svg">';
        item.prepend(icon);
    }

    // topCatagories[1].classList.add('opened');
</script>
