<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit);
$customClass = $block->getClassName();
?>

<?php if ($customClass): ?>
    <nav class="<?php echo $customClass ?>" data-action="navigation">
<?php else: ?>
    <nav class="navigation" data-action="navigation">
<?php endif; ?>
    <ul data-init="navigation">
        <?= /* @noEscape */ $_menuHtml?>
        <?= $block->getChildHtml() ?>
    </ul>
</nav>
