<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */
    $viewMode ?> products-<?= /* @noEscape */
    $viewMode ?>">
        <div class="marker">Just the list.phtml</div>
        <!-- plist 123 -->
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <li class="item product product-item">
                    <div class="product-item-info"
                         id="product-item-info_<?= /* @noEscape */
                         $_product->getId() ?>"
                         data-container="product-<?= /* @noEscape */
                         $viewMode ?>">

                        <!-- Labels left -->

                        <div class="product-item__label-left-container">
                            <div class="product-item__label-left sale">
                                <span><?= $block->escapeHtml(__('Sale')) ?></span>
                            </div>
                            <div class="product-item__label-left new">
                                <span><?= $block->escapeHtml(__('New')) ?></span>
                            </div>
                        </div>

                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        if ($pos != null) {
                            $position = 'left:' . $productImage->getWidth() . 'px;' . 'top:' . $productImage->getHeight() . 'px;';
                        }
                        ?>

                        <?php // Product Image ?>
                        <div class="product-item-photo-outer">
                            <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                               class="product photo product-item-photo"
                               tabindex="-1">
                                <?= $productImage->toHtml() ?>
                            </a>
                        </div>
                        <div class="product details product-item-details">
                            <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                    <?= /* @noEscape */
                                    $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </strong>
                            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>

                            <div class="category-link">
                                <a href="#" class="category-link__href"><span>Just Bagel</span></a>
                            </div>

                            <div class="fin-block">
                                <div class="price-here">
                                    <?= $block->getProductPrice($_product) ?>
                                    <span class="price-here__weight">/<span>100g</span></span>
                                </div>

                                <div class="product-item-actions">
                                    <?php if ($_product->isSaleable()): ?>
                                        <div class="calc-cell-container">
                                            <div class="calc-cell calculator">
                                                <div class="custom-qty-btn btn-minus"><span>-</span></div>
                                                <input type="text" value="1" class="input-text qty custom"
                                                       data-mage-init='{"custom.plusMinus":{"buttons": false, "limit": 10000}}'>
                                                <div class="custom-qty-btn btn-plus"><span>+</span></div>
                                            </div>
                                            <div class="add-to-calc calc-cell">
                                                <button class="add-to-calc__button"><span>Add to</span></button>
                                            </div>
                                        </div>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available">
                                                <span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable">
                                                <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <?= ($pos && strpos($pos, $viewMode . '-primary')) ? /* @noEscape */
                                            $secureRenderer->renderStyleAsTag($position, 'product-item-info_' . $_product->getId() . ' div.actions-primary') : '' ?>
                                    <?= ($pos && strpos($pos, $viewMode . '-secondary')) ? /* @noEscape */
                                            $secureRenderer->renderStyleAsTag($position, 'product-item-info_' . $_product->getId() . ' div.actions-secondary') : '' ?>
                                </div>

                            </div>

                        </div>
                    </div>
                    <?= ($pos && strpos($pos, $viewMode . '-actions')) ? /* @noEscape */
                            $secureRenderer->renderStyleAsTag($position, 'product-item-info_' . $_product->getId() . ' div.product-item-actions') : '' ?>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate ?>
    <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
                }
            },
            "*": {
                "js/category-scripts": {}
            }
        }
    </script>
<?php endif; ?>
