<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */
    $viewMode ?> products-<?= /* @noEscape */
    $viewMode ?>">
        <!-- plist 123 -->
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <li class="item product product-item">
                    <div class="product-item-info"
                         id="product-item-info_<?= /* @noEscape */
                         $_product->getId() ?>"
                         data-container="product-<?= /* @noEscape */
                         $viewMode ?>">
                        <!-- Labels left -->

                        <div class="product-item__label-left-container">
                            <div class="product-item__label-left sale">
                                <span><?= $escaper->escapeHtml(__('Sale')) ?></span>
                            </div>
                            <div class="product-item__label-left new">
                                <span><?= $escaper->escapeHtml(__('New')) ?></span>
                            </div>
                        </div>

                        <!-- get Sku -->
                        <div class="hidden-sku" data-sku="<?= $_product->getSku() ?>"><?= $_product->getSku() ?></div>
                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        if ($pos != null) {
                            $position = 'left:' . $productImage->getWidth() . 'px;' . 'top:' . $productImage->getHeight() . 'px;';
                        }
                        ?>

                        <?php // Product Image ?>
                        <div class="product-item-photo-outer">
                            <figure data-href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                               class="product photo product-item-photo"
                               tabindex="-1">
                                <?= $productImage->toHtml() ?>
                            </figure>
                        </div>
                        <div class="product details product-item-details">
                            <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                            <strong class="product name product-item-name">
                                <span class="product-item-link"
                                   data-href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                    <?= /* @noEscape */
                                    $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </span>
                            </strong>
                            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>

                            <div class="category-link">
                                <a href="#" class="category-link__href"><span><?= $_product->getAttributeText('manufacturer') ?></span></a>
                            </div>

                            <div class="fin-block">
                                <div class="price-here">
                                    <?= $block->getProductPrice($_product) ?>
                                    <span class="price-here__weight">/<span><?= (float)$_product->getData("singleweight") * 1000; ?><?= $block->escapeHtml(__('gr')) ?></span></span>
                                </div>

                                <div class="product-item-actions">
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form"
                                              data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                              action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                              data-mage-init='{"catalogAddToCart": {}}'
                                              method="post">
                                            <?php $options = $block->getData('viewModel')->getOptionsData($_product); ?>
                                            <?php foreach ($options as $optionItem): ?>
                                                <input type="hidden"
                                                       name="<?= $escaper->escapeHtml($optionItem['name']) ?>"
                                                       value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
                                            <?php endforeach; ?>
                                            <input type="hidden"
                                                   name="product"
                                                   value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                            <input type="hidden"
                                                   name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                   value="<?=
                                                   /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                                    ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <div class="calc-cell-container">
                                                <div class="calc-cell calculator">
                                                    <div class="custom-qty-btn btn-minus"><span>-</span></div>
                                                    <input 
                                                        data-mage-init='{
                                                            "custom.plusMinus":{
                                                                "buttons": false, 
                                                                "limit": 1000, 
                                                                "productId" : "<?php echo $_product->getId(); ?>",
                                                                "updateQtyUrl" : "<?php echo $block->getUrl("checkout/sidebar/updateItemQty"); ?>",
                                                                "removeItemUrl" : "<?php echo $block->getUrl("checkout/sidebar/removeItem"); ?>"
                                                            }}' 
                                                        type="number" 
                                                        name="qty"
                                                        min="1" 
                                                        value="1" class="product-quantity input-text qty custom">
                                                    <div class="custom-qty-btn btn-plus"><span>+</span></div>
                                                </div>
                                                <div class="add-to-calc calc-cell">
                                                    <button type="submit"
                                                            title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                            class="action tocart primary add-to-calc__button" 
                                                            disabled>
                                                        <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                    </button>
                                                </div>
                                            </div>
                                        </form>
                                        
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available">
                                                <span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable">
                                                <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <?= ($pos && strpos($pos, $viewMode . '-primary')) ? /* @noEscape */
                                            $secureRenderer->renderStyleAsTag($position, 'product-item-info_' . $_product->getId() . ' div.actions-primary') : '' ?>
                                    <?= ($pos && strpos($pos, $viewMode . '-secondary')) ? /* @noEscape */
                                            $secureRenderer->renderStyleAsTag($position, 'product-item-info_' . $_product->getId() . ' div.actions-secondary') : '' ?>
                                </div>

                            </div>

                        </div>
                    </div>
                    <?= ($pos && strpos($pos, $viewMode . '-actions')) ? /* @noEscape */
                            $secureRenderer->renderStyleAsTag($position, 'product-item-info_' . $_product->getId() . ' div.product-item-actions') : '' ?>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate ?>
    <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
                }
            }
        }
    </script>
<?php endif; ?>
