<?php
/*
 * Customer authorization
 */

/** @var \Magento\Framework\App\ObjectManager $om */
$om = \Magento\Framework\App\ObjectManager::getInstance();
/** @var \Magento\Framework\App\Http\Context $context */
$context = $om->get('Magento\Framework\App\Http\Context');
/** @var bool $isLoggedIn */
$isLoggedIn = $context->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH);
?>

<div class="header-login-block" data-popup-container>

    <?php if ($isLoggedIn): ?>
        <!-- Logged in-->
        <div class="account-button" data-popup-trigger><span><?= __('account') ?></span></div>
        <div class="ko-customer-menu" data-target="dropdown" aria-hidden="false" data-popup-content>
            <ul>
                <li>
                    <a href="<?php echo $block->getBaseUrl(); ?>/customer/account/" id="idi3GyRLlJ"><?= __('My Account') ?></a></li>
                <li class="link authorization-link" data-label="or">
                    <a href="<?php echo $block->getBaseUrl(); ?>/customer/account/logout/"><?= __('Sign Out') ?></a>
                </li>
            </ul>
        </div>
    <?php else: ?>
        <!-- Not logged in -->
        <a href="<?php echo $block->getBaseUrl(); ?>/customer/account/login/" class="login-button">
            <span><?= __('Log In') ?></span>
        </a>
    <?php endif; ?>

</div>

<script type="text/x-magento-init">
    {
        ".header-login-block": {
            "custon.dropdown": {
                "speed": 0
            }
        }
    }
</script>

