<?php
/**
 * @var $viewModel Kosher\CustomerAdjustment\ViewModel\CustomerLoginViewModel
 * @var $block Magento\Framework\View\Element\Template
 */

$viewModel = $block->getViewModel();
?>

<div class="header-login-block" data-popup-container>

    <?php if ($viewModel->isCustomerLogin()): ?>
        <!-- Logged in-->
        <div class="account-button mobile" data-popup-trigger><span><?= __('account') ?></span></div>
        <div class="account-button desktop" data-popup-trigger>
            <span><?= $viewModel->getCustomerName() ?></span>
        </div>
        <div class="ko-customer-menu" data-target="dropdown" aria-hidden="false" data-popup-content>
            <ul>
                <li>
                    <a href="<?php echo $block->getBaseUrl(); ?>customer/account/" id="my-account"><?= __('My Account') ?></a>
                </li>
                <li>
                    <a href="<?php echo $block->getBaseUrl(); ?>sales/order/history/" id="history"><?= __('My Orders') ?></a>
                </li>
                <li class="link authorization-link" data-label="or">
                    <a href="<?php echo $block->getBaseUrl(); ?>customer/account/logout/"><?= __('Sign Out') ?></a>
                </li>
            </ul>
        </div>
    <?php else: ?>
        <!-- Not logged in -->
        <a href="<?php echo $block->getBaseUrl(); ?>/customer/account/login/" class="login-button">
            <span><?= __('Log In') ?></span>
        </a>
    <?php endif; ?>

</div>

<script type="text/x-magento-init">
    {
        ".header-login-block": {
            "custon.dropdown": {
                "speed": 0
            }
        }
    }
</script>


