<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */

// phpcs:disable Generic.Files.LineLength.TooLong
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
    <div class="block-products-list grid-slider">
        <!--  gridslider 44    -->
        <div class="block-content">
            <?= /* @noEscape */
            '<!-- ' . $image . '-->' ?>
            <div class="products-grid">
                <ol class="product-items products widget-product-grid">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?= /* @noEscape */
                        ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info">

                            <!-- Label left -->

                            <div class="product-item__label-left-container">
                                <div class="product-item__label-left sale">
                                    <span><?= $block->escapeHtml(__('Sale')) ?></span>
                                </div>
                                <div class="product-item__label-left new">
                                    <span><?= $block->escapeHtml(__('New')) ?></span>
                                </div>
                            </div>

                            <!-- Photo -->
                            <div class="product-item-photo-outer">
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                            </div>

                            <!-- get Sku -->
                            <div class="hidden-sku" data-sku="<?= $_item->getSku() ?>"><?= $_item->getSku() ?></div>

                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>

                                <?php if ($templateType): ?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <div class="category-link">
                                    <a href="#" class="category-link__href"><span>Just Bagel</span></a>
                                </div>

                                <div class="fin-block">

                                    <div class="price-here">
                                        <?= $block->getProductPriceHtml($_item, $type) ?>
                                        <span class="price-here__weight">/<span>100g</span></span>
                                    </div>

                                    <?php if ($showWishlist || $showCompare || $showCart): ?>
                                        <div class="product-item-actions">
                                            <?php if ($showCart): ?>
                                                <?php if ($_item->isSaleable()): ?>
                                                    <div class="calc-cell-container">
                                                        <div class="calc-cell calculator">
                                                            <div class="custom-qty-btn btn-minus"><span>-</span></div>
                                                            <input type="number" value="1" class="input-text qty custom"
                                                                   data-mage-init='{"custom.plusMinus":{"buttons": false, "limit": 1000}}'>
                                                            <div class="custom-qty-btn btn-plus"><span>+</span></div>
                                                        </div>
                                                        <div class="add-to-calc calc-cell">
                                                            <button class="add-to-calc__button"><span>Add to</span></button>
                                                        </div>
                                                    </div>
                                                <?php else: ?>
                                                    <?php if ($_item->isAvailable()): ?>
                                                        <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>

                                </div>
                            </div>
                        </div>
                        <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
        </div>
    </div>

    <script type="text/x-magento-init">
            {
                ".page-main .widget-product-grid": {
                    "js/widgets/home-sliders.widget": {}
                }
            }
    </script>

    <?php if ($block->getBlockHtml('formkey')): ?>
        <script type="text/x-magento-init">
            {
                ".widget-product-grid": {
                    "Magento_Catalog/js/validate-product": {}
                }
            }
        </script>
    <?php endif; ?>

<?php endif; ?>

