<?php
use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
/**
 * @var $escaper \Magento\Framework\Escaper
 */
// phpcs:disable Generic.Files.LineLength.TooLong
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
    <div class="block-products-list grid-slider">
        <!--  gridslider 44    -->
        <div class="block-content">
            <?= /* @noEscape */
            '<!-- ' . $image . '-->' ?>
            <div class="products-grid">
                <ol class="product-items products widget-product-grid">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?= /* @noEscape */
                        ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info">

                            <!-- Label left -->

                            <div class="product-item__label-left-container">
                                <div class="product-item__label-left sale">
                                    <span><?= $escaper->escapeHtml(__('Sale')) ?></span>
                                </div>
                                <div class="product-item__label-left new">
                                    <span><?= $escaper->escapeHtml(__('New')) ?></span>
                                </div>
                            </div>

                            <!-- Photo -->
                            <div class="product-item-photo-outer">
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                            </div>

                            <!-- get Sku -->
                            <div class="hidden-sku" data-sku="<?= $_item->getSku() ?>"><?= $_item->getSku() ?></div>

                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>

                                <?php if ($templateType): ?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?php if ($manufacturer = $_item->getAttributeText('manufacturer')): ?>
                                    <div class="category-link">
                                        <a href="<?= $escaper->escapeUrl(__('/catalogsearch/result/?q=%1', $manufacturer)) ?>" class="category-link__href">
                                            <span><?= /* @noEscape */ $manufacturer ?></span>
                                        </a>
                                    </div>
                                <?php endif; ?>

                                <div class="fin-block">

                                    <div class="price-here">
                                        <?= $block->getProductPriceHtml($_item, $type) ?>
                                        <span class="price-here__weight">/<span><?= (float)$_item->getData("singleweight") * 1000; ?><?= $escaper->escapeHtml(__('gr')) ?></span></span>
                                    </div>

                                    <?php if ($showWishlist || $showCompare || $showCart): ?>
                                        <div class="product-item-actions">
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                <form data-role="tocart-form" data-product-sku="<?= $escaper->escapeHtml($_item->getSku()) ?>" action="<?= $escaper->escapeUrl($postParams['action']) ?>" method="post">
                                                    <input type="hidden" name="product" value="<?= $escaper->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                    <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <div class="calc-cell-container">
                                                        <div class="calc-cell calculator">
                                                            <div class="custom-qty-btn btn-minus"><span>-</span></div>
                                                            <input 
                                                                data-mage-init='{
                                                                    "custom.plusMinus":{
                                                                        "buttons": false, 
                                                                        "limit": 1000, 
                                                                        "productId" : "<?php echo $_item->getId(); ?>",
                                                                        "updateQtyUrl" : "<?php echo $block->getUrl("checkout/sidebar/updateItemQty"); ?>",
                                                                        "removeItemUrl" : "<?php echo $block->getUrl("checkout/sidebar/removeItem"); ?>"
                                                                    }}' 
                                                                type="number" 
                                                                name="qty"
                                                                min="1" 
                                                                value="1" class="product-quantity input-text qty custom">
                                                            <div class="custom-qty-btn btn-plus"><span>+</span></div>
                                                        </div>
                                                        <div class="add-to-calc calc-cell">
                                                            <button type="submit"
                                                                    title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                    class="action tocart primary add-to-calc__button" 
                                                                    disabled>
                                                                <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                            </button>
                                                        </div>
                                                    </div>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_item->isAvailable()): ?>
                                                    <div class="stock available"><span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>

                                </div>
                            </div>
                        </div>
                        <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
        </div>
    </div>

<?php endif; ?>