<?php
/**
 * PDP popup
 */
declare(strict_types=1);

use Kosher\ProductPopup\ViewModel\GetCurretProductSkuViewModel;
use Magento\Backend\Block\Template;
use Magento\Framework\Escaper;

/**
 * @var Template $block
 * @var GetCurretProductSkuViewModel $viewModel
 * @var Escaper $escaper
 */

$viewModel = $block->getViewModel();
$productSku = $viewModel->getProductSku();
if ($productSku) {
    $storeUrl = $viewModel->getStoreUrl();
    $apiUrl = $viewModel->getProductBySkuRequest();
    $requestUrl = $storeUrl . $apiUrl;
}
$productSku = '043427181129';
$storeUrl = $viewModel->getStoreUrl();
$apiUrl = $viewModel->getProductBySkuRequest();
$requestUrl = $storeUrl . $apiUrl;
?>
<div class="k4u-popup">
    <a href="#" class="k4u-popup__close" id="k4u_popup_close"><span><?= $escaper->escapeHtml(__('Close')) ?></span></a>
    <div class="k4u-popup__product-container">
        <div class="k4u-popup__inner">

        </div>
    </div>
    <div class="k4u-popup__slider-container">

        <div class="k4u-popup__slider-container-header">
            <h4><?= $escaper->escapeHtml(__('Similar Products')) ?></h4>
            <a href="#"><?= $escaper->escapeHtml(__('See All')) ?></a>
        </div>

        <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('popup-slider')->toHtml(); ?>

    </div>

</div>
<script type="text/x-magento-init">
    {
        ".catalog-category-view .page-main .product-items.products": {
            "pdp.popup": {
                "apiURL": "<?= $requestUrl ?>"
            }
        },
        ".catalogsearch-result-index .page-main .product-items.products": {
            "pdp.popup": {
                "apiURL": "<?= $requestUrl ?>"
            }
        },
        ".page-main .home-interactive.special .product-items.products": {
            "pdp.popup": {
                "apiURL": "<?= $requestUrl ?>"
            }
        }
    }

</script>
