<?php

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

?>

<?php

/**
 * @var Escaper $escaper  
 * @var Template $block 
 */
?>
<form action="" method="post" id="form-validate" class="form send confirmation" data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <div class="field email required">
            <label for="email_address" class="label"><span><?= $escaper->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" name="email" placeholder="<?= $escaper->escapeHtml(__('Email')) ?>" id="email_address" class="input-text" value="<?= $escaper->escapeHtmlAttr($block->getEmail()) ?>" data-validate="{required:true, 'validate-email':true}" data-mage-init='{"mage/trim-input":{}}'>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action send primary"><span><?= $escaper->escapeHtml(__('Send confirmation link')) ?></span></button>
        </div>
        <div class="secondary">
            <a href="<?= $block->escapeUrl($block->getLoginUrl()) ?>" class="action back"><span><?= $escaper->escapeHtml(__('Back to Sign In')) ?></span></a>
        </div>
    </div>
</form>
