<?php
// @codingStandardsIgnoreFile

/* @var $block \Mirasvit\Credit\Block\Link */
?>
<?php if ($block->isCustomerLoggedIn()): ?>
        <a <?= $block->getLinkAttributes() ?>  class="store-credit__container" data-bind="scope: 'credit'">
            <div class="store-credit__title"><?= $block->escapeHtml($block->getLabel()) ?></div>
            <!-- ko if: credit().amount -->
            <div data-bind="text: credit().amount" class="store-credit__price"></div>
            <!-- /ko -->
            <div class="store-credit__close"><span><?= __('Close') ?></span></div>
        </a>
<?php endif; ?>


<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "credit": {
                        "component": "Mirasvit_Credit/js/view/credit"
                    }
                }
            }
        }
    }
</script>
