<section class="plp-section">

    <div class="plp-filters-col">
        <div class="plp-filters">
            <button class="hide-filters" id="hide_filters"><span>Close</span></button>
            <img src="<?= /** @noEscape */ $block->getViewFileUrl('images/unsorted/filters-01.png') ?>" alt="Filters">
        </div>
    </div>

    <div class="plp-listing">
        <div class="page-title-wrapper">
            <h1 class="page-title" id="page-title-heading" aria-labelledby="page-title-heading toolbar-amount">
                <span class="base" data-ui-id="page-title-wrapper">Daily Fresh</span></h1>
        </div>

        <p>
            On todistettu, että lukijaa häiritsee sivun ulkoasu lukiessaan sivua. Lorem Ipsumin käytön tarkoitus on, että se omaa enemmän-tai-vähemmän normaalimpaa sanojen sijoitusta kuin 'Sisältöä tähän, sisältöä tähän'. Monet tietokoneen julkistusohjelmien pakkaukset ja nettisivueditorit käyttävät nyt Lorem Ipsumia heidän normaalina mallitekstinä. 'Lorem Ipsumia' etsittäessä löytyy monen monta nettisivua, jotka ovat vasta aluillaan. Useita versioita on muodostunut vuosien kuluessa, jotkut vahingossa ja jotkut tarkoituksella (lisätty huumoria ja niin edelleen).
        </p>

        <div class="toolbar toolbar-products">

           <button class="show-filter" id="show_filters"><span>Filter</span></button>
        </div>

        <div class="products wrapper grid products-grid">
            <ul class="products-list">
                <li class="product-cell"><h4>Product here</h4></li>
                <li class="product-cell"><h4>Product here</h4></li>
                <li class="product-cell"><h4>Product here</h4></li>
                <li class="product-cell"><h4>Product here</h4></li>
                <li class="product-cell"><h4>Product here</h4></li>
                <li class="product-cell"><h4>Product here</h4></li>
                <li class="product-cell"><h4>Product here</h4></li>
                <li class="product-cell"><h4>Product here</h4></li>
                <li class="product-cell"><h4>Product here</h4></li>
                <li class="product-cell"><h4>Product here</h4></li>
                <li class="product-cell"><h4>Product here</h4></li>
                <li class="product-cell"><h4>Product here</h4></li>
                <li class="product-cell"><h4>Product here</h4></li>
                <li class="product-cell"><h4>Product here</h4></li>
                <li class="product-cell"><h4>Product here</h4></li>
                <li class="product-cell"><h4>Product here</h4></li>
            </ul>
        </div>
    </div>

</section>
