<script type="text/x-magento-init">
    {
        "*": {
            "main": {
            }
        },
        ".kosher-main-menu": {
            "custom.accordion": {
                "speed": 200,
                "triggerClass": ".level0.category-item .level-top",
                "contentClass": ".submenu"
            }
        }
    }
</script>

<script>
    // Genarating menu images. Remove it
    let topCatagories = document.querySelectorAll('.kosher-main-menu .level0.category-item > a.level-top');

    for (let item of topCatagories) {
        let icon = document.createElement('div');
        icon.classList.add('category-icon');
        icon.innerHTML = '<img src="/static/frontend/Kosher/default/en_US/images/categories/groceries.svg">';
        item.prepend(icon);
    }

    let menuCategories = document.querySelectorAll('.kosher-horizontal-menu .level0.category-item > a.level-top');

    for (let item of menuCategories) {
        let icon = document.createElement('div');
        icon.classList.add('category-icon');
        icon.innerHTML = '<img src="/static/frontend/Kosher/default/en_US/images/categories/groceries.svg">';
        item.prepend(icon);
    }

    let storeCreditBtn = document.querySelector('.page-wrapper > .store-credit__container');

    let storeCreditActive = () => {
        setTimeout(() => {
            storeCreditBtn.classList.add('active')
        }, 1000)
    };

    storeCreditBtn.addEventListener('click', function () {
        sessionStorage.setItem('hideStoreCreditBtn', true);
        this.classList.remove('active');
    });

    !sessionStorage.getItem('hideStoreCreditBtn') ? storeCreditActive() : null;

</script>
