<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>
<?php if ($block->getRegistration()->isAllowed()) : ?>
    <div class="block-new-customer">
        <h4 title="<?= $block->escapeHtml(__('Don’t have an  Kosher4u account?')) ?>"><?= $block->escapeHtml(__('Don’t have an  Kosher4u account?')) ?></h4>
        <a href="<?= $block->escapeUrl($block->getCreateAccountUrl()) ?>" class="action create primary"><span><?= $block->escapeHtml(__('Sigh up')) ?></span></a>
    </div>
<?php endif; ?>
