<?php
declare(strict_types=1);

use Kosher\CategoryAdjustment\ViewModel\ProductNavigationViewModel;
use Magento\Backend\Block\Template;
?>
<?php
/**
 * @var Template $block
 * @var ProductNavigationViewModel $viewModel
 */
?>

<nav class="navigation">
    <ul>
        <?php
        $urlParameter = $block->getData('url_parameter');
        $viewModel = $block->getData('view_model');
        $topCategories = $viewModel->getTopCategoriesForStore();
        foreach ($topCategories as $category) {

            $url = $category->getUrl() . '?show=' . $urlParameter;
            $isActive = $block->getHtmlClass() == 'level-top' ? '' : '';
            $iconUrl = $viewModel->getIconPathForCategory($category);
            ?>
            <li class="level0 nav-1 category-item">
                <a class="level-top" href="<?php echo $url; ?>">
                    <?php if ($iconUrl): ?>
                        <img class="category-icon" src="<?php echo $block->escapeUrl($iconUrl); ?>"
                             alt="<?php echo $block->escapeHtmlAttr($category->getName()); ?>"/>
                    <?php endif; ?>
                    <span>
                    <?php echo $block->escapeHtml($category->getName()); ?>
                </span>
                </a>
            </li>
            <?php
        }
        ?>
    </ul>
</nav>
