<?php

use Magento\Catalog\Block\Product\View\Attributes;
use Magento\Framework\Escaper;

?>

<?php

/**
 * Product additional attributes template
 *
 * @var Attributes $block
 * @var Escaper $escaper
 */
?>
<?php
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
    $_product = $block->getProduct();
?>

<?php if ($_additional = $block->getAdditionalData()) :?>
    <div class="attributes-top">
        <?php foreach ($_additional as $_data) :?>
            <?php if($_data['code'] === 'singleweight'): ?>
                <?= $escaper->escapeHtml(__('Weight, gr.')) ?>
                <?= /* @noEscape */ (
                    $_helper->productAttribute($_product, $_data['value'], $_data['code']) * 1000
                    ) ?>
            <?php endif; ?>
            <?php if($_data['code'] === 'weight'): ?>
                (
                <?= $escaper->escapeHtml(__('Shipping weight')) ?>
                <?php if(($_helper->productAttribute($_product, $_data['value'], $_data['code']) * 1000) < 1000): ?>
                    <?= /* @noEscape */ ($_helper->productAttribute($_product, $_data['value'], $_data['code']) * 1000) ?> g
                <?php else: ?>
                    <?= /* @noEscape */ ($_helper->productAttribute($_product, $_data['value'], $_data['code']) / 1000) ?> kg
                <?php endif; ?>
                ) 
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
<?php endif;?>
