<?php

use Magento\Catalog\Block\Product\View\Description;
use Magento\Framework\Escaper;

?>

<?php

/**
 * Product view template
 *
 * @var Description $block
 * @var Escaper $escaper
 */
?>

<?php
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();

if (!$_product instanceof \Magento\Catalog\Model\Product) {
    return;
}

$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

$renderLabel = true;
// if defined as 'none' in layout, do not render
if ($_attributeLabel == 'none') {
    $renderLabel = false;
}

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getStoreLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code))
        ? $_product->getAttributeText($_code)
        : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>

<?php if ($_attributeValue) :?>
<div class="product attribute <?= $block->escapeHtmlAttr($_className) ?>">
    <?php if ($renderLabel) :?>
        <strong class="type">
            <?php if($block->escapeHtml($_attributeLabel) === 'SKU'): ?>
                <?= $escaper->escapeHtml(__('Barcode:')) ?>
            <?php else: ?>
                <?= $block->escapeHtml($_attributeLabel) ?>
            <?php endif; ?>
        </strong>
    <?php endif; ?>
    <div class="value" <?= /* @noEscape */ $_attributeAddAttribute ?>>
        <?php if($block->escapeHtmlAttr($_className) === 'overview'): ?>
            <strong>
                <?= $escaper->escapeHtml(__('Ingredients:')) ?>
            </strong>
            <?= strip_tags($_attributeValue) ?>
        <?php else: ?>
            <?= /* @noEscape */ $_attributeValue ?>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>