<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<?php if ($block->getCollection()->getSize()) : ?>
    <?php $widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($block->getWidgetOptionsJson());
    $widgetOptions = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($widget['productListToolbarForm']);
    ?>
    <div class="toolbar-panel">
        <div class="toolbar toolbar-products" data-mage-init='{"productListToolbarForm":<?= /* @noEscape */
        $widgetOptions ?>}'>
            <?php if ($block->getIsBottom()): ?>
                <?= $block->getPagerHtml() ?>
                <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>
            <?php else: ?>
                <div class="filter-button">
                    <button class="show-filter-button" id="show_filters_button"><span><?= $block->escapeHtml(__('Filter')) ?></span></button>
                </div>
                <div class="center-cell">
                    <?php if ($block->isExpanded()): ?>
                        <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
                    <?php endif ?>
                    <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>
                </div>
                <?php if ($block->isExpanded()): ?>
                    <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
                <?php endif ?>
            <?php endif ?>
        </div>
    </div>
<?php endif ?>
